[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "networkx>=2.6.3",
    "inflect",
    "numpy>=1.20",
    "humanize",
    "matplotlib",
    "shapefile",
    "tabulate",
]
build-backend = "setuptools.build_meta"